repos:
  - repo: local
    hooks:
      - id: trailing-whitespace
        name: trailing whitespace
        entry: trailing-whitespace-fixer
        language: system
        types: [text]
      - id: end-of-file-fixer
        name: end of files
        entry: end-of-file-fixer
        language: system
        types: [text]
      - id: check-yaml
        name: check yaml
        entry: check-yaml
        language: system
      - id: check-added-large-files
        name: check added large files
        entry: check-added-large-files
        language: system
      - id: check-merge-conflict
        name: check merge conflict
        entry: check-merge-conflict
        language: system
      - id: debug-statements
        name: debug statements (python)
        entry: debug-statements
        language: system
        types: [python]
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [--line-length=88]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: [--profile=black]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: [--max-line-length=88, --extend-ignore=E203,W503] 